### PR TITLE
support aarch64

### PR DESCRIPTION
**Pull request by goroya**
add support  aarch64.
I checked compile success on Jetson TX2(aarch64).

### CODE REVIEW

**Comment by j1elo** [comment]
Hi,

please also test with latest version of upstream project:
https://github.com/vmarkovtsev/DeathHandler

(just copy the new files on top of the ones in Kurento, and change the `#include "death_handler.h"` to `#include "death_handler.hpp"`.

If it works, please open a PR in upstream project, maybe linking to this one. Kurento will soon move on to the latest version of upstream so it will be good if this addition is already in there.

**Comment by SurionAndrew** [comment]
Good Day, 

@j1elo 
from what I can see:
"j1elo merged commit 0a5e285 into Kurento:master on 12 Mar 2019" this was merged into master

how would one install KMS on l4t system jetson tx1/tx1 Xavier board? 

In the Install instructions there is a hint at arch

> sudo tee "/etc/apt/sources.list.d/kurento.list" >/dev/null <<EOF
# Kurento Media Server - Release packages
deb [arch=amd64] http://ubuntu.openvidu.io/6.13.0 $DISTRO kms6
EOF

Would we try:
replace arch=amd64 with arch=aarch64 ?

or does this require compiling from source

Regards Andrew

**Comment by j1elo** [comment]
You have to compile from source. The Kurento project only maintains apt repositories for amd64 architecture (Ubuntu 16.04 and 18.04 as of now).

**Comment by SurionAndrew** [comment]
Thank you,

Ill give it a try

**Pull request merged**
